export const KYC_PROGRAM_ID_TESTNET = "DKS4RNuTQheBr2AdRQCYVKPKQk4nyY19jmp3dB6UH3Wf";
export const KYC_PROGRAM_ID_MAINNET = "";
export const KYC_PROGRAM_ID_LOCALHOST = "DKS4RNuTQheBr2AdRQCYVKPKQk4nyY19jmp3dB6UH3Wf";