export const KYC_PROGRAM_ID_TESTNET = "DKS4RNuTQheBr2AdRQCYVKPKQk4nyY19jmp3dB6UH3Wf";
export const KYC_PROGRAM_ID_MAINNET = "";
export const KYC_PROGRAM_ID_LOCALHOST = "DKS4RNuTQheBr2AdRQCYVKPKQk4nyY19jmp3dB6UH3Wf";
export const REID_MINT_TESTNET = "7juGZx8v5TQbbfKLkgn5gAQkWrocWoKADVYXegtBi6Jm";
export const REID_MINT_MAINNET = "";
export const RENEC_PROVIDER_TESTNET = "DWf39ga2tvvqh1xJAD8t5nepCE6opM9tW6Lzhwj3oF5x";
export const RENEC_PROVIDER_MAINNET = "";